### ISSUE TITLE
Crashed on windows with ImportError: cannot import name 'List' from 'typing_extensions'

### ISSUE THREAD

**Issue by snomiao** [Comfy-Org/comfy-cli#59]
**Describe the bug**
Crashed with ImportError: cannot import name 'List' from 'typing_extensions'

**To Reproduce**

```bat
pip install comfy-cli
comfy-cli
```

**But** i'm not sure if it's able to reproduce. It's possible my environment got sth wrong

- [ ] TODO: Try again with conda venv.

**Expected behavior**

**Nice to have**
- [x] Terminal output
- [ ] Screenshots

**Additional context**

OS: Windows 10 LTSC 21H2
![image](https://github.com/yoland68/comfy-cli/assets/7323030/6c6d1b2a-4d50-4d19-be08-7382686178f3)

Python 3.10.7

```log

C:\Users\snomi>python --version
Python 3.10.7

C:\Users\snomi>comfy-cli
Traceback (most recent call last):
  File "C:\Users\snomi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\snomi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\snomi\AppData\Local\Programs\Python\Python310\Scripts\comfy-cli.exe\__main__.py", line 4, in <module>
  File "C:\Users\snomi\AppData\Local\Programs\Python\Python310\lib\site-packages\comfy_cli\__main__.py", line 1, in <module>
    from comfy_cli.cmdline import main
  File "C:\Users\snomi\AppData\Local\Programs\Python\Python310\lib\site-packages\comfy_cli\cmdline.py", line 13, in <module>
    from typing_extensions import Annotated, List
ImportError: cannot import name 'List' from 'typing_extensions' (C:\Users\snomi\AppData\Roaming\Python\Python310\site-packages\typing_extensions.py)

C:\Users\snomi>pip install comfy-cli
Requirement already satisfied: comfy-cli in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (0.0.22)
Requirement already satisfied: typer>=0.3.0 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from comfy-cli) (0.7.0)
Requirement already satisfied: GitPython in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from comfy-cli) (3.1.31)
Requirement already satisfied: rich in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from comfy-cli) (13.7.1)
Requirement already satisfied: requests in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from comfy-cli) (2.28.2)
Requirement already satisfied: pyyaml in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from comfy-cli) (6.0)
Requirement already satisfied: typing-extensions in c:\users\snomi\appdata\roaming\python\python310\site-packages (from comfy-cli) (4.5.0)
Requirement already satisfied: mixpanel in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from comfy-cli) (4.10.1)
Requirement already satisfied: questionary in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from comfy-cli) (2.0.1)
Requirement already satisfied: psutil in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from comfy-cli) (5.9.3)
Requirement already satisfied: tomlkit in c:\users\snomi\appdata\roaming\python\python310\site-packages (from comfy-cli) (0.11.6)
Requirement already satisfied: pathspec in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from comfy-cli) (0.11.1)
Requirement already satisfied: httpx in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from comfy-cli) (0.24.0)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from typer>=0.3.0->comfy-cli) (8.1.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from GitPython->comfy-cli) (4.0.10)
Requirement already satisfied: certifi in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from httpx->comfy-cli) (2021.5.30)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from httpx->comfy-cli) (0.17.0)
Requirement already satisfied: idna in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from httpx->comfy-cli) (3.4)
Requirement already satisfied: sniffio in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from httpx->comfy-cli) (1.3.0)
Requirement already satisfied: six>=1.9.0 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from mixpanel->comfy-cli) (1.16.0)
Requirement already satisfied: urllib3 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from mixpanel->comfy-cli) (1.26.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from requests->comfy-cli) (2.1.1)
Requirement already satisfied: prompt_toolkit<=3.0.36,>=2.0 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from questionary->comfy-cli) (3.0.31)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from rich->comfy-cli) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from rich->comfy-cli) (2.13.0)
Requirement already satisfied: colorama in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from click<9.0.0,>=7.1.1->typer>=0.3.0->comfy-cli) (0.4.6)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from gitdb<5,>=4.0.1->GitPython->comfy-cli) (5.0.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx->comfy-cli) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx->comfy-cli) (3.6.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich->comfy-cli) (0.1.2)
Requirement already satisfied: wcwidth in c:\users\snomi\appdata\local\programs\python\python310\lib\site-packages (from prompt_toolkit<=3.0.36,>=2.0->questionary->comfy-cli) (0.2.5)

```

**Comment by yoland68** [comment]
Can you help take a look?
