### ISSUE TITLE
Just installed and fails out of the box

### ISSUE THREAD

**Issue by iamwavecut** [Comfy-Org/comfy-cli#69]
**Describe the bug**
```
Traceback (most recent call last):
  File "/home/x/.local/bin/comfy", line 5, in <module>
    from comfy_cli.__main__ import main
  File "/home/x/.local/lib/python3.10/site-packages/comfy_cli/__main__.py", line 1, in <module>
    from comfy_cli.cmdline import main
  File "/home/x/.local/lib/python3.10/site-packages/comfy_cli/cmdline.py", line 16, in <module>
    from comfy_cli.command import custom_nodes
  File "/home/x/.local/lib/python3.10/site-packages/comfy_cli/command/__init__.py", line 1, in <module>
    from . import custom_nodes
  File "/home/x/.local/lib/python3.10/site-packages/comfy_cli/command/custom_nodes/__init__.py", line 1, in <module>
    from .command import app, manager_app
  File "/home/x/.local/lib/python3.10/site-packages/comfy_cli/command/custom_nodes/command.py", line 103, in <module>
    typer.Option(
TypeError: Option() missing 1 required positional argument: 'default'
```

**To Reproduce**
run `comfy install`

**Expected behavior**
Installation of ComfyUI and manager should happen

**Nice to have**
- [x] Terminal output
- [ ] Screenshots

**Additional context**
```
❯
ls -la
total 28
drwxrwxrwx 1 root root    48 May 20 10:19 .
drwxrwxrwx 1 root root 28672 May 19 23:47 ..

❯
neofetch
            .-/+oossssoo+/-.               x@x
        `:+ssssssssssssssssss+:`           --------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.4 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: B550M-ITX/ac
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.5.0-35-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 days, 12 hours, 25 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2486 (dpkg), 15 (flatpak), 13 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8.1
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 3440x1440
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: /dev/pts/4
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: AMD Ryzen 5 5600G with Radeon Graphics (12) @ 4.464GHz
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: NVIDIA 01:00.0 NVIDIA Corporation Device 2805
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 14407MiB / 63655MiB
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
            

❯
nvidia-smi
Mon May 20 10:24:08 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti     On  | 00000000:01:00.0  On |                  N/A |
| 43%   44C    P2              33W / 165W |   9268MiB / 16380MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1329      G   /usr/lib/xorg/Xorg                          128MiB |
|    0   N/A  N/A      7430      G   budgie-wm                                    83MiB |
|    0   N/A  N/A    472755      C   python                                     9044MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by ltdrdata** [comment]
Can you show the typer package version?
`pip freeze | grep typer`

**Comment by robinjhuang** [comment]
@iamwavecut Can you try installing the latest version and see if you still have this issue?

**Comment by iamwavecut** [comment]
Fixed for me. I am not able to reproduce the exact scenario but it works after updating to latest cli. Thanks @robinjhuang !
